AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 25

Style/StringLiterals:
  EnforcedStyle: single_quotes
